#!/bin/bash
killall -q wireplumber
killall -q pipewire-pulse
killall -q pipewire
pipewire &
export QT_QPA_PLATFORM=xcb &
pgrep -x sxhkd > /dev/null || sxhkd &
~/.fehbg &
pgrep -x dunst > /dev/null || dunst &
pgrep -x polkit-gnome > /dev/null || /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
setxkbmap br &
xset r rate 300 30 &
pgrep -x compfy > /dev/null || compfy &
pgrep -x udiskie > /dev/null || udiskie -s &
pgrep -f /usr/bin/blugon > /dev/null || blugon -f &
sleep 1
pipewire-pulse &
wireplumber &
~/.config/polybar/launch.sh &
pgrep -x btops > /dev/null || btops &

bspc config border_width         2
bspc config window_gap           8
bspc config automatic_scheme     alternate
bspc config normal_border_color  "#a89984"
bspc config focused_border_color "#fe8019"

bspc config split_ratio          0.5
bspc config borderless_monocle   false
bspc config gapless_monocle      false

bspc rule -a gnome-calculator state=floating
bspc rule -a steam_app_306130 state=pseudo_tiled
bspc rule -a leagueclientux.exe state=pseudo_tiled
