#! /bin/sh
export QT_QPA_PLATFORM=xcb &
killall -q pipewire; pipewire &
pgrep -x sxhkd > /dev/null || sxhkd &
~/.fehbg &
pgrep -x dunst > /dev/null || dunst &
pgrep -x polkit-gnome > /dev/null || /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
setxkbmap br &
xset r rate 300 30 &
pgrep -x compfy > /dev/null || compfy &
pgrep -x udiskie > /dev/null || udiskie -s &
blugon -f &
caffeine-indicator &
sleep 1
killall -q pipewire-pulse; pipewire-pulse &
~/.config/polybar/launch.sh &
btops &
killall -q wireplumber; wireplumber &

bspc config border_width         2
bspc config window_gap           8
bspc config automatic_scheme     alternate
bspc config normal_border_color  "#a89984"
bspc config focused_border_color "#fe8019"

bspc config split_ratio          0.5
bspc config borderless_monocle   false
bspc config gapless_monocle      false

bspc rule -a gnome-calculator state=floating
bspc rule -a steam_app_306130 state=pseudo_tiled
bspc rule -a leagueclientux.exe state=pseudo_tiled
