remove-empty = true
remove-focused = false

renamers = ["classified", "client", "constant"]

[names]
constant = " 󰐕 "

[[names.classified]]
"| " = ["kitty", "Alacritty"]
"| " = ["LibreWolf"]
"| " = ["firefox-esr", "firefox", "org.mozilla.firefox"]
"|󰙯 " = ["discord"]
"|󰺵 " = ["leagueclient.exe", "leagueclientux.exe", "league of legends.exe", "steam_app_306130", "riotclientservices.exe", "Lutris", "glaclient-linux"]
"|󰓓 " = ["steam"]
"|󱢾 " = ["heroic"]
"| " = ["jetbrains-datagrip"]
"|󱐋 " = ["blitz.exe"]
"| " = ["Insomnia"]
"| " = ["ONLYOFFICE"]
"|󱡫 " = ["qpwgraph"]
"|󰍯 " = ["NoiseTorch"]
"|󱜠 " = ["obs"]
"| " = ["TelegramDesktop"]
"|󰋊 " = ["Gnome-disks", "GParted"]
"| " = ["Stremio"]
"| " = ["looking-glass-client"]
"| " = ["Nextcloud"]
"| " = ["qt6ct", "qt5ct", "Kvantum Manager", "Lxappearance"]
"| " = ["Nvidia-settings"]
"| " = ["deepin-calculator"]
"|󱃖 " = ["dev.zed.Zed"]
"|󰖟 " = ["Navegador"]
"|󱫬 " = ["Timeshift-gtk"]
"|󱅧 " = ["Lxpolkit"]
